import { LucideFileSpreadsheet } from "lucide-react";
import {
  FaApple,
  FaBed,
  FaBicycle,
  FaBlender,
  FaBookReader,
  FaBriefcaseMedical,
  FaCamera,
  FaCar,
  FaCouch,
  FaDrumstickBite,
  FaHeadphones,
  FaLaptop,
  FaMobileAlt,
  FaPencilAlt,
  FaPrescriptionBottleAlt,
  FaShoppingCart,
  FaToolbox,
  FaTshirt,
  FaTv,
  FaUmbrellaBeach,
  FaWineGlassAlt,
} from "react-icons/fa";
import {
  GiCampingTent,
  GiCoffeeCup,
  GiElectric,
  GiGuitar,
  GiSofa,
} from "react-icons/gi";
import {
  IoFastFood,
  IoFootballSharp,
  IoReaderSharp,
  IoSchool,
  IoShirt,
  IoTabletPortrait,
} from "react-icons/io5";
import {
  MdOutlinePhonelink,
  MdOutlineSportsSoccer,
  MdOutlineSportsTennis,
  MdPets,
} from "react-icons/md";
import { BsPhone, BsWatch } from "react-icons/bs";
import { AiFillGift } from "react-icons/ai";

export const icons = [
  { id: 1, icon: <FaBookReader />, isSelected: true },
  { id: 2, icon: <IoReaderSharp />, isSelected: false },
  { id: 3, icon: <LucideFileSpreadsheet />, isSelected: false },
  { id: 4, icon: <FaShoppingCart />, isSelected: false },
  { id: 5, icon: <FaLaptop />, isSelected: false },
  { id: 6, icon: <FaMobileAlt />, isSelected: false },
  { id: 7, icon: <IoTabletPortrait />, isSelected: false },
  { id: 8, icon: <FaCar />, isSelected: false },
  { id: 9, icon: <FaTshirt />, isSelected: false },
  { id: 10, icon: <IoShirt />, isSelected: false },
  { id: 11, icon: <FaPencilAlt />, isSelected: false },
  { id: 12, icon: <FaCamera />, isSelected: false },
  { id: 13, icon: <FaHeadphones />, isSelected: false },
  { id: 14, icon: <FaApple />, isSelected: false },
  { id: 15, icon: <FaBriefcaseMedical />, isSelected: false },
  { id: 16, icon: <FaBlender />, isSelected: false },
  { id: 17, icon: <GiSofa />, isSelected: false },
  { id: 18, icon: <FaCouch />, isSelected: false },
  { id: 19, icon: <FaUmbrellaBeach />, isSelected: false },
  { id: 20, icon: <FaBlender />, isSelected: false },
  { id: 21, icon: <IoFootballSharp />, isSelected: false },
  { id: 22, icon: <FaToolbox />, isSelected: false },
  { id: 23, icon: <GiElectric />, isSelected: false },
  { id: 24, icon: <FaTv />, isSelected: false },
  { id: 25, icon: <MdOutlineSportsSoccer />, isSelected: false },
  { id: 26, icon: <MdOutlineSportsTennis />, isSelected: false },
  { id: 27, icon: <FaBed />, isSelected: false },
  { id: 28, icon: <FaDrumstickBite />, isSelected: false },
  { id: 29, icon: <GiCoffeeCup />, isSelected: false },
  { id: 30, icon: <GiGuitar />, isSelected: false },
  { id: 31, icon: <MdPets />, isSelected: false },
  { id: 32, icon: <IoSchool />, isSelected: false },
  { id: 33, icon: <MdOutlinePhonelink />, isSelected: false },
  { id: 34, icon: <FaPrescriptionBottleAlt />, isSelected: false },
  { id: 35, icon: <FaBicycle />, isSelected: false },
  { id: 36, icon: <FaWineGlassAlt />, isSelected: false },
  { id: 37, icon: <IoFastFood />, isSelected: false },
  { id: 38, icon: <BsPhone />, isSelected: false },
  { id: 39, icon: <BsWatch />, isSelected: false },
  { id: 40, icon: <AiFillGift />, isSelected: false },
  { id: 41, icon: <GiCampingTent />, isSelected: false },
];
