"use client";

import { Product } from "./columns";
import {
  MdBuild,
  MdInventory,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
} from "react-icons/md";

export const productData: Product[] = [
  {
    id: 1,
    name: "Screwdriver",
    supplier: "ToolSupplier Inc.",
    sku: "SD123",
    category: "Other",
    status: "Draft",
    quantityInStock: 50,
    price: 600,
    icon: MdBuild,
  },
  {
    id: 2,
    name: "Hammer",
    supplier: "ToolSupplier Inc.",
    sku: "HM123",
    category: "Other",
    status: "Published",
    quantityInStock: 100,
    price: 800,
    icon: MdBuild,
  },
  {
    id: 3,
    name: "iPhone 16",
    supplier: "Appliances",
    sku: "DR123",
    category: "Other",
    status: "Inactive",
    quantityInStock: 30,
    price: 15000,
    icon: MdPhoneIphone,
  },
  {
    id: 4,
    name: "jackets",
    supplier: "zudio",
    sku: "ZT123",
    category: "Clothing",
    status: "Published",
    quantityInStock: 30,
    price: 1500,
    icon: MdInventory,
  },
  {
    id: 5,
    name: "Laptop",
    supplier: "Dell",
    sku: "DL123",
    category: "Electronics",
    status: "Published",
    quantityInStock: 20,
    price: 50000,
    icon: MdLaptop,
  },
  {
    id: 6,
    name: "Microwave",
    supplier: "Samsung",
    sku: "SM123",
    category: "Home Appliances",
    status: "Published",
    quantityInStock: 10,
    price: 10000,
    icon: MdKitchen,
  },
  {
    id: 7,
    name: "Sofa",
    supplier: "Furniture",
    sku: "FR123",
    category: "Furniture",
    status: "Published",
    quantityInStock: 5,
    price: 20000,
    icon: MdHome,
  },
  {
    id: 8,
    name: "Atomic Habits",
    supplier: "Books",
    sku: "BK123",
    category: "Books",
    status: "Published",
    quantityInStock: 10,
    price: 500,
    icon: MdInventory,
  },
  {
    id: 9,
    name: "T-shirt",
    supplier: "Clothing",
    sku: "CT123",
    category: "Clothing",
    status: "Published",
    quantityInStock: 50,
    price: 500,
    icon: MdInventory,
  },
  {
    id: 10,
    name: "Football",
    supplier: "Sports",
    sku: "SP123",
    category: "Sports",
    status: "Published",
    quantityInStock: 20,
    price: 1000,
    icon: MdInventory,
  },
  {
    id: 11,
    name: "Lipstick",
    supplier: "Beauty",
    sku: "BT123",
    category: "Beauty",
    status: "Published",
    quantityInStock: 30,
    price: 200,
    icon: MdInventory,
  },
];
